<?php

namespace Cartxis\Core\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $countries = [
            ['AF', 'AFG', 'Afghanistan', '+93', 'AFN', '؋'],
            ['AL', 'ALB', 'Albania', '+355', 'ALL', 'L'],
            ['DZ', 'DZA', 'Algeria', '+213', 'DZD', 'د.ج'],
            ['AS', 'ASM', 'American Samoa', '+1-684', 'USD', '$'],
            ['AD', 'AND', 'Andorra', '+376', 'EUR', '€'],
            ['AO', 'AGO', 'Angola', '+244', 'AOA', 'Kz'],
            ['AI', 'AIA', 'Anguilla', '+1-264', 'XCD', '$'],
            ['AG', 'ATG', 'Antigua and Barbuda', '+1-268', 'XCD', '$'],
            ['AR', 'ARG', 'Argentina', '+54', 'ARS', '$'],
            ['AM', 'ARM', 'Armenia', '+374', 'AMD', '֏'],
            ['AW', 'ABW', 'Aruba', '+297', 'AWG', 'ƒ'],
            ['AU', 'AUS', 'Australia', '+61', 'AUD', '$'],
            ['AT', 'AUT', 'Austria', '+43', 'EUR', '€'],
            ['AZ', 'AZE', 'Azerbaijan', '+994', 'AZN', '₼'],
            ['BS', 'BHS', 'Bahamas', '+1-242', 'BSD', '$'],
            ['BH', 'BHR', 'Bahrain', '+973', 'BHD', '.د.ب'],
            ['BD', 'BGD', 'Bangladesh', '+880', 'BDT', '৳'],
            ['BB', 'BRB', 'Barbados', '+1-246', 'BBD', '$'],
            ['BY', 'BLR', 'Belarus', '+375', 'BYN', 'Br'],
            ['BE', 'BEL', 'Belgium', '+32', 'EUR', '€'],
            ['BZ', 'BLZ', 'Belize', '+501', 'BZD', '$'],
            ['BJ', 'BEN', 'Benin', '+229', 'XOF', 'CFA'],
            ['BM', 'BMU', 'Bermuda', '+1-441', 'BMD', '$'],
            ['BT', 'BTN', 'Bhutan', '+975', 'BTN', 'Nu.'],
            ['BO', 'BOL', 'Bolivia', '+591', 'BOB', 'Bs.'],
            ['BA', 'BIH', 'Bosnia and Herzegovina', '+387', 'BAM', 'KM'],
            ['BW', 'BWA', 'Botswana', '+267', 'BWP', 'P'],
            ['BR', 'BRA', 'Brazil', '+55', 'BRL', 'R$'],
            ['BN', 'BRN', 'Brunei', '+673', 'BND', '$'],
            ['BG', 'BGR', 'Bulgaria', '+359', 'BGN', 'лв'],
            ['BF', 'BFA', 'Burkina Faso', '+226', 'XOF', 'CFA'],
            ['BI', 'BDI', 'Burundi', '+257', 'BIF', 'FBu'],
            ['CV', 'CPV', 'Cabo Verde', '+238', 'CVE', '$'],
            ['KH', 'KHM', 'Cambodia', '+855', 'KHR', '៛'],
            ['CM', 'CMR', 'Cameroon', '+237', 'XAF', 'FCFA'],
            ['CA', 'CAN', 'Canada', '+1', 'CAD', '$'],
            ['KY', 'CYM', 'Cayman Islands', '+1-345', 'KYD', '$'],
            ['CF', 'CAF', 'Central African Republic', '+236', 'XAF', 'FCFA'],
            ['TD', 'TCD', 'Chad', '+235', 'XAF', 'FCFA'],
            ['CL', 'CHL', 'Chile', '+56', 'CLP', '$'],
            ['CN', 'CHN', 'China', '+86', 'CNY', '¥'],
            ['CO', 'COL', 'Colombia', '+57', 'COP', '$'],
            ['KM', 'COM', 'Comoros', '+269', 'KMF', 'CF'],
            ['CG', 'COG', 'Congo', '+242', 'XAF', 'FCFA'],
            ['CD', 'COD', 'Congo (DRC)', '+243', 'CDF', 'FC'],
            ['CR', 'CRI', 'Costa Rica', '+506', 'CRC', '₡'],
            ['CI', 'CIV', "Côte d'Ivoire", '+225', 'XOF', 'CFA'],
            ['HR', 'HRV', 'Croatia', '+385', 'EUR', '€'],
            ['CU', 'CUB', 'Cuba', '+53', 'CUP', '$'],
            ['CY', 'CYP', 'Cyprus', '+357', 'EUR', '€'],
            ['CZ', 'CZE', 'Czech Republic', '+420', 'CZK', 'Kč'],
            ['DK', 'DNK', 'Denmark', '+45', 'DKK', 'kr'],
            ['DJ', 'DJI', 'Djibouti', '+253', 'DJF', 'Fdj'],
            ['DM', 'DMA', 'Dominica', '+1-767', 'XCD', '$'],
            ['DO', 'DOM', 'Dominican Republic', '+1-809', 'DOP', '$'],
            ['EC', 'ECU', 'Ecuador', '+593', 'USD', '$'],
            ['EG', 'EGY', 'Egypt', '+20', 'EGP', '£'],
            ['SV', 'SLV', 'El Salvador', '+503', 'USD', '$'],
            ['GQ', 'GNQ', 'Equatorial Guinea', '+240', 'XAF', 'FCFA'],
            ['ER', 'ERI', 'Eritrea', '+291', 'ERN', 'Nfk'],
            ['EE', 'EST', 'Estonia', '+372', 'EUR', '€'],
            ['SZ', 'SWZ', 'Eswatini', '+268', 'SZL', 'E'],
            ['ET', 'ETH', 'Ethiopia', '+251', 'ETB', 'Br'],
            ['FJ', 'FJI', 'Fiji', '+679', 'FJD', '$'],
            ['FI', 'FIN', 'Finland', '+358', 'EUR', '€'],
            ['FR', 'FRA', 'France', '+33', 'EUR', '€'],
            ['GA', 'GAB', 'Gabon', '+241', 'XAF', 'FCFA'],
            ['GM', 'GMB', 'Gambia', '+220', 'GMD', 'D'],
            ['GE', 'GEO', 'Georgia', '+995', 'GEL', '₾'],
            ['DE', 'DEU', 'Germany', '+49', 'EUR', '€'],
            ['GH', 'GHA', 'Ghana', '+233', 'GHS', '₵'],
            ['GR', 'GRC', 'Greece', '+30', 'EUR', '€'],
            ['GD', 'GRD', 'Grenada', '+1-473', 'XCD', '$'],
            ['GT', 'GTM', 'Guatemala', '+502', 'GTQ', 'Q'],
            ['GN', 'GIN', 'Guinea', '+224', 'GNF', 'FG'],
            ['GW', 'GNB', 'Guinea-Bissau', '+245', 'XOF', 'CFA'],
            ['GY', 'GUY', 'Guyana', '+592', 'GYD', '$'],
            ['HT', 'HTI', 'Haiti', '+509', 'HTG', 'G'],
            ['HN', 'HND', 'Honduras', '+504', 'HNL', 'L'],
            ['HK', 'HKG', 'Hong Kong', '+852', 'HKD', '$'],
            ['HU', 'HUN', 'Hungary', '+36', 'HUF', 'Ft'],
            ['IS', 'ISL', 'Iceland', '+354', 'ISK', 'kr'],
            ['IN', 'IND', 'India', '+91', 'INR', '₹'],
            ['ID', 'IDN', 'Indonesia', '+62', 'IDR', 'Rp'],
            ['IR', 'IRN', 'Iran', '+98', 'IRR', '﷼'],
            ['IQ', 'IRQ', 'Iraq', '+964', 'IQD', 'ع.د'],
            ['IE', 'IRL', 'Ireland', '+353', 'EUR', '€'],
            ['IL', 'ISR', 'Israel', '+972', 'ILS', '₪'],
            ['IT', 'ITA', 'Italy', '+39', 'EUR', '€'],
            ['JM', 'JAM', 'Jamaica', '+1-876', 'JMD', '$'],
            ['JP', 'JPN', 'Japan', '+81', 'JPY', '¥'],
            ['JO', 'JOR', 'Jordan', '+962', 'JOD', 'د.ا'],
            ['KZ', 'KAZ', 'Kazakhstan', '+7', 'KZT', '₸'],
            ['KE', 'KEN', 'Kenya', '+254', 'KES', 'KSh'],
            ['KI', 'KIR', 'Kiribati', '+686', 'AUD', '$'],
            ['KP', 'PRK', 'Korea (North)', '+850', 'KPW', '₩'],
            ['KR', 'KOR', 'Korea (South)', '+82', 'KRW', '₩'],
            ['KW', 'KWT', 'Kuwait', '+965', 'KWD', 'د.ك'],
            ['KG', 'KGZ', 'Kyrgyzstan', '+996', 'KGS', 'лв'],
            ['LA', 'LAO', 'Laos', '+856', 'LAK', '₭'],
            ['LV', 'LVA', 'Latvia', '+371', 'EUR', '€'],
            ['LB', 'LBN', 'Lebanon', '+961', 'LBP', 'ل.ل'],
            ['LS', 'LSO', 'Lesotho', '+266', 'LSL', 'L'],
            ['LR', 'LBR', 'Liberia', '+231', 'LRD', '$'],
            ['LY', 'LBY', 'Libya', '+218', 'LYD', 'ل.د'],
            ['LI', 'LIE', 'Liechtenstein', '+423', 'CHF', 'CHF'],
            ['LT', 'LTU', 'Lithuania', '+370', 'EUR', '€'],
            ['LU', 'LUX', 'Luxembourg', '+352', 'EUR', '€'],
            ['MO', 'MAC', 'Macao', '+853', 'MOP', 'MOP$'],
            ['MG', 'MDG', 'Madagascar', '+261', 'MGA', 'Ar'],
            ['MW', 'MWI', 'Malawi', '+265', 'MWK', 'MK'],
            ['MY', 'MYS', 'Malaysia', '+60', 'MYR', 'RM'],
            ['MV', 'MDV', 'Maldives', '+960', 'MVR', 'Rf'],
            ['ML', 'MLI', 'Mali', '+223', 'XOF', 'CFA'],
            ['MT', 'MLT', 'Malta', '+356', 'EUR', '€'],
            ['MH', 'MHL', 'Marshall Islands', '+692', 'USD', '$'],
            ['MR', 'MRT', 'Mauritania', '+222', 'MRU', 'UM'],
            ['MU', 'MUS', 'Mauritius', '+230', 'MUR', '₨'],
            ['MX', 'MEX', 'Mexico', '+52', 'MXN', '$'],
            ['FM', 'FSM', 'Micronesia', '+691', 'USD', '$'],
            ['MD', 'MDA', 'Moldova', '+373', 'MDL', 'L'],
            ['MC', 'MCO', 'Monaco', '+377', 'EUR', '€'],
            ['MN', 'MNG', 'Mongolia', '+976', 'MNT', '₮'],
            ['ME', 'MNE', 'Montenegro', '+382', 'EUR', '€'],
            ['MA', 'MAR', 'Morocco', '+212', 'MAD', 'د.م.'],
            ['MZ', 'MOZ', 'Mozambique', '+258', 'MZN', 'MT'],
            ['MM', 'MMR', 'Myanmar', '+95', 'MMK', 'K'],
            ['NA', 'NAM', 'Namibia', '+264', 'NAD', '$'],
            ['NR', 'NRU', 'Nauru', '+674', 'AUD', '$'],
            ['NP', 'NPL', 'Nepal', '+977', 'NPR', '₨'],
            ['NL', 'NLD', 'Netherlands', '+31', 'EUR', '€'],
            ['NZ', 'NZL', 'New Zealand', '+64', 'NZD', '$'],
            ['NI', 'NIC', 'Nicaragua', '+505', 'NIO', 'C$'],
            ['NE', 'NER', 'Niger', '+227', 'XOF', 'CFA'],
            ['NG', 'NGA', 'Nigeria', '+234', 'NGN', '₦'],
            ['MK', 'MKD', 'North Macedonia', '+389', 'MKD', 'ден'],
            ['NO', 'NOR', 'Norway', '+47', 'NOK', 'kr'],
            ['OM', 'OMN', 'Oman', '+968', 'OMR', 'ر.ع.'],
            ['PK', 'PAK', 'Pakistan', '+92', 'PKR', '₨'],
            ['PW', 'PLW', 'Palau', '+680', 'USD', '$'],
            ['PS', 'PSE', 'Palestine', '+970', 'ILS', '₪'],
            ['PA', 'PAN', 'Panama', '+507', 'PAB', 'B/.'],
            ['PG', 'PNG', 'Papua New Guinea', '+675', 'PGK', 'K'],
            ['PY', 'PRY', 'Paraguay', '+595', 'PYG', '₲'],
            ['PE', 'PER', 'Peru', '+51', 'PEN', 'S/.'],
            ['PH', 'PHL', 'Philippines', '+63', 'PHP', '₱'],
            ['PL', 'POL', 'Poland', '+48', 'PLN', 'zł'],
            ['PT', 'PRT', 'Portugal', '+351', 'EUR', '€'],
            ['PR', 'PRI', 'Puerto Rico', '+1-787', 'USD', '$'],
            ['QA', 'QAT', 'Qatar', '+974', 'QAR', 'ر.ق'],
            ['RO', 'ROU', 'Romania', '+40', 'RON', 'lei'],
            ['RU', 'RUS', 'Russia', '+7', 'RUB', '₽'],
            ['RW', 'RWA', 'Rwanda', '+250', 'RWF', 'RF'],
            ['KN', 'KNA', 'Saint Kitts and Nevis', '+1-869', 'XCD', '$'],
            ['LC', 'LCA', 'Saint Lucia', '+1-758', 'XCD', '$'],
            ['VC', 'VCT', 'Saint Vincent and the Grenadines', '+1-784', 'XCD', '$'],
            ['WS', 'WSM', 'Samoa', '+685', 'WST', 'T'],
            ['SM', 'SMR', 'San Marino', '+378', 'EUR', '€'],
            ['ST', 'STP', 'São Tomé and Príncipe', '+239', 'STN', 'Db'],
            ['SA', 'SAU', 'Saudi Arabia', '+966', 'SAR', 'ر.س'],
            ['SN', 'SEN', 'Senegal', '+221', 'XOF', 'CFA'],
            ['RS', 'SRB', 'Serbia', '+381', 'RSD', 'дин.'],
            ['SC', 'SYC', 'Seychelles', '+248', 'SCR', '₨'],
            ['SL', 'SLE', 'Sierra Leone', '+232', 'SLL', 'Le'],
            ['SG', 'SGP', 'Singapore', '+65', 'SGD', '$'],
            ['SK', 'SVK', 'Slovakia', '+421', 'EUR', '€'],
            ['SI', 'SVN', 'Slovenia', '+386', 'EUR', '€'],
            ['SB', 'SLB', 'Solomon Islands', '+677', 'SBD', '$'],
            ['SO', 'SOM', 'Somalia', '+252', 'SOS', 'Sh'],
            ['ZA', 'ZAF', 'South Africa', '+27', 'ZAR', 'R'],
            ['SS', 'SSD', 'South Sudan', '+211', 'SSP', '£'],
            ['ES', 'ESP', 'Spain', '+34', 'EUR', '€'],
            ['LK', 'LKA', 'Sri Lanka', '+94', 'LKR', '₨'],
            ['SD', 'SDN', 'Sudan', '+249', 'SDG', 'ج.س.'],
            ['SR', 'SUR', 'Suriname', '+597', 'SRD', '$'],
            ['SE', 'SWE', 'Sweden', '+46', 'SEK', 'kr'],
            ['CH', 'CHE', 'Switzerland', '+41', 'CHF', 'CHF'],
            ['SY', 'SYR', 'Syria', '+963', 'SYP', '£'],
            ['TW', 'TWN', 'Taiwan', '+886', 'TWD', 'NT$'],
            ['TJ', 'TJK', 'Tajikistan', '+992', 'TJS', 'SM'],
            ['TZ', 'TZA', 'Tanzania', '+255', 'TZS', 'TSh'],
            ['TH', 'THA', 'Thailand', '+66', 'THB', '฿'],
            ['TL', 'TLS', 'Timor-Leste', '+670', 'USD', '$'],
            ['TG', 'TGO', 'Togo', '+228', 'XOF', 'CFA'],
            ['TO', 'TON', 'Tonga', '+676', 'TOP', 'T$'],
            ['TT', 'TTO', 'Trinidad and Tobago', '+1-868', 'TTD', '$'],
            ['TN', 'TUN', 'Tunisia', '+216', 'TND', 'د.ت'],
            ['TR', 'TUR', 'Turkey', '+90', 'TRY', '₺'],
            ['TM', 'TKM', 'Turkmenistan', '+993', 'TMT', 'T'],
            ['TV', 'TUV', 'Tuvalu', '+688', 'AUD', '$'],
            ['UG', 'UGA', 'Uganda', '+256', 'UGX', 'USh'],
            ['UA', 'UKR', 'Ukraine', '+380', 'UAH', '₴'],
            ['AE', 'ARE', 'United Arab Emirates', '+971', 'AED', 'د.إ'],
            ['GB', 'GBR', 'United Kingdom', '+44', 'GBP', '£'],
            ['US', 'USA', 'United States', '+1', 'USD', '$'],
            ['UY', 'URY', 'Uruguay', '+598', 'UYU', '$'],
            ['UZ', 'UZB', 'Uzbekistan', '+998', 'UZS', 'сўм'],
            ['VU', 'VUT', 'Vanuatu', '+678', 'VUV', 'VT'],
            ['VA', 'VAT', 'Vatican City', '+379', 'EUR', '€'],
            ['VE', 'VEN', 'Venezuela', '+58', 'VES', 'Bs.S'],
            ['VN', 'VNM', 'Vietnam', '+84', 'VND', '₫'],
            ['YE', 'YEM', 'Yemen', '+967', 'YER', '﷼'],
            ['ZM', 'ZMB', 'Zambia', '+260', 'ZMW', 'ZK'],
            ['ZW', 'ZWE', 'Zimbabwe', '+263', 'ZWL', '$'],
        ];

        $rows = [];
        foreach ($countries as $i => $c) {
            $rows[] = [
                'code'            => $c[0],
                'code3'           => $c[1],
                'name'            => $c[2],
                'phone_code'      => $c[3],
                'currency_code'   => $c[4],
                'currency_symbol' => $c[5],
                'is_active'       => true,
                'sort_order'      => 0,
                'created_at'      => $now,
                'updated_at'      => $now,
            ];
        }

        // Insert in chunks
        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('countries')->insert($chunk);
        }
    }
}
